server:
  port: 8080
  servlet:
    context-path: /book

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java_booky
    username: vax
    password: vakporize
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format-sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


ng:
  com:
    createsoftware:
      secret: VAXXINESECRETKEY
      expiration: 86400000
